<?php 
$datas = $viewData['users'];
?>
<h1 class="page-header">Users</h1>

<a href="/user/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
    <?php foreach($datas as $id => $data):?>
        <tr>
           <?php 
            //$user = explode(",", $user);
            foreach ($data as $value):?>               
                <td><?php echo $value;?></td>
            <?php endforeach; ?>
            <td>
                <a href="/user/update/iduser/<?=$data['iduser'];?>">Update</a> | 
                <a href="/user/delete/iduser/<?=$data['iduser'];?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>